### PR TITLE
feat: add options for editor and templates

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- Add options (to change in the modals) for editor and templates:
  - auto saving
  - delay for auto saving in msc
  - auto rendering
- Add info about modified document in the terminal
- Improve readonly view - when someone pass as query parameters `readOnly` and some url, or base64

WDYT? @mcturco @boyney123 @jonaslagoni 

**Related issue(s)**
Resolves https://github.com/asyncapi/studio/issues/137

### CODE REVIEW

**Comment by jonaslagoni** [comment]
> Add options (to change in the modals) for editor and templates:
>     * auto saving
>     * delay for auto saving in msc
>     * auto rendering

Love it 👍

**Comment by mcturco** [comment]
@magicmatatjahu how can I visually see the changes that were made? I know there is a netlify preview link, but what actions do I have to take to review the changes in the preview?

**Comment by magicmatatjahu** [comment]
@mcturco Yeah, sorry, I didn't describe how to test it in the preview. In the left-bottom corner we have a gear icon, which open the modal with settings. You can change (atm) settings for editor and templates:

image

You can change e.g. editor autosaving and then you should see:

image

`Auto saving` which indicates that editor will auto save changes to the local storage

Or (if you disabled auto saving):

image

`Modified` which indicates that you changed your spec and you should save it :)

Also for editor there is `auto-rendering` option which indicates that rendering will be done automatically or by yourself, there will be button in the sidebar of the right panel:

image

**Comment by mcturco** [comment]
@magicmatatjahu thank you so much for outlining the changes! These are great improvements, well done. However, the only thing that I found myself slightly confused about is when Autosaving is turned on I was expecting for the `Successfully saved to local storage` banner to pop up after the set autosave delay. Then, I think that the `! Autosaving` notice should disappear OR maybe we change the `! Autosaving` to `Autosave: On` that way it is a bit more clear that it is indeed working -- the current label looks more like a warning to me. What do you think?

**Comment by magicmatatjahu** [comment]
@mcturco Thanks for comment and thanks for kindly words :) 

I did it this way in the first iteration, but then it turned out that with frequent changes, this notification with information that was saved, appeared too often and it did not look good. We can return to this solution with a delay for saving, ie if someone makes several changes within 5 seconds, only once will appear this notification. 

About note, right it looks a bit like a warning, but I guess it is a warning that affects the way you "use" the studio, right? :) But we can change it to `Autosave: On` (and maybe also `Autosave: Off` in case of disabled function?). I will make that changes and I ping you :)

**Comment by magicmatatjahu** [comment]
@mcturco Ok, I propagated changes, you can see them in new preview :)

**Comment by mcturco** [comment]
> I did it this way in the first iteration, but then it turned out that with frequent changes, this notification with information that was saved, appeared too often and it did not look good.

@magicmatatjahu okay I definitely see what you are saying here and I have to agree now when I visually see it. Figma (the design program I use) always autosaves work automatically and how they handle the notification is that it only shows up when you use the "Save" keyboard shortcut (Command + S / Ctrl + S). Perhaps when Autosave is turned on, the notification can say:

`Studio is currently saving your work automatically 💪 `

And when Autosave is turned off, the notification remains the same as it is now. Let me know if this makes sense and what your thoughts are on it.

**Comment by mcturco** [comment]
@magicmatatjahu correct, I just tested it writing a whole sentence and if I hesitated at all the banner would show up which I think might be a little excessive now that I am seeing it happen. If you think about it, users currently are used to hitting the "Save" keyboard shortcut for most programs to save their progress, so I think showing that banner `Studio is currently saving your work automatically 💪` will be enough of an indicator that they don't have to keep saving manually. You know what I mean?

**Comment by magicmatatjahu** [comment]
@mcturco Thanks for clarification, I understand. I will add that notification, but also I will leave that info in the terminal `Autosave: On` and `Autosave: Off` :)

**Comment by magicmatatjahu** [comment]
@mcturco Thanks! You can check changes in the preview. Let me know if everything is ok :)

**Review by mcturco — APPROVED** [review]
@magicmatatjahu I think this works! Thank you!

**Comment by boyney123** [comment]
Looking good!

image

@magicmatatjahu @mcturco I wonder if we should add descriptions to the features in the settings (mocked above), for example, I'm not sure what `Auto rendering` means, so having some small description to help would help me at least 😅 (hopefully others too).

That does get me thinking long term too, about the Studio, and docs on how to use it and future features going forward. I think maybe one day we should have some external docs about the Studio, it's features, and how to get the most out of it. @alequetzalli any thoughts there?

**Comment by mcturco** [comment]
> @magicmatatjahu @mcturco I wonder if we should add descriptions to the features in the settings (mocked above)

I think this is a great idea @boyney123! Something short and sweet to let the user know what the function of that option is. 👍

**Comment by alequetzalli** [comment]
> That does get me thinking long term too, about the Studio, and docs on how to use it and future features going forward. I think maybe one day we should have some external docs about the Studio, it's features, and how to get the most out of it. @alequetzalli any thoughts there?


That's correct, Studio (like all over Tools in the Initiative) will require Docs, and those Docs will go under the `/Tools` content bucket of our Docs. 

This will be the same as other Docs contributions :)

**Comment by magicmatatjahu** [comment]
@boyney123 @mcturco Ok, I added descriptions :) Please check in the preview.

image

**Comment by mcturco** [comment]
@magicmatatjahu looks great!

Sorry but I have one more thing... the current UI for the on/off switch to toggle on and off the autosaving & auto-rendering to me is a little bit confusing. I couldn't immediately tell if it was turned on or off, so I am proposing this new UI style for the switches:

Screen Shot 2021-12-14 at 10 12 16 AM

Let me know if this is achievable!

**Comment by mcturco** [comment]
@magicmatatjahu PERFECT 🤩

**Comment by magicmatatjahu** [comment]
@mcturco Hah , you're fast 😆  I was going to write to you about change 😄

**Comment by mcturco** [comment]
@magicmatatjahu I get all the email notifications 😆

**Review by mcturco — DISMISSED** [review]

**Comment by magicmatatjahu** [comment]
@mcturco so you saw my activity on weekend when I contribute to the panels/tabs 😱

**Comment by mcturco** [comment]
@magicmatatjahu yes, I see EVERYTHING... 🤣

**Comment by magicmatatjahu** [comment]
@boyney123 Do you wanna add something more? :)

**Comment by boyney123** [comment]
Nice stuff @magicmatatjahu, wish I was as fast as @mcturco ! haha

Yeah just a minor UX thing (maybe), I see some options are related to the parent option (if turned on), I know future we will have more settings and options, I wonder if we should have them sit under the parent option.

What I mean is like this

image

Just slightly indicates that that 2nd option is only related to the first one if its on. Maybe even disable the option if the its off?

image

Not sure. Just an idea. What you think @magicmatatjahu @mcturco .

---

Apart from that looking great! Guess I should review the code... but maybe I will after we finished with any UI/UX changes.

**Comment by magicmatatjahu** [comment]
@boyney123 @mcturco Changes propagated, thanks Dave for awesome suggestion! :)

**Comment by mcturco** [comment]
@boyney123 @magicmatatjahu  I think this is a great suggestion and definitely works. Perhaps in the future we can iterate on that when more options are added.

**Review by boyney123 — APPROVED** [review]

**Pull request merged**
