### PR TITLE
chore: add playground redirects

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Add playground redirects.

### CODE REVIEW

**Comment by fmvilas** [comment]
It seems possible to preserve query parameters: https://answers.netlify.com/t/preserve-query-parameters-on-redirect/2226/7. You only have to list them all 😅 Luckily we don't have a lot 🙂

**Comment by magicmatatjahu** [comment]
@fmvilas Yeah... 😅 I added redirects and I also tested them in https://play.netlify.com/redirects and config is valid :) Could you look?

**Comment by fmvilas** [comment]
Oh man :facepalm: 😆

**Comment by magicmatatjahu** [comment]
@fmvilas You can change DNS :)

**Comment by fmvilas** [comment]
Done! 🎉 👉 https://playground.asyncapi.io

**Pull request merged**
