### PR TITLE
feat: initial try to get the parser working

### PR DESCRIPTION
**Pull request by Shurtu-gal**
**Description**

- Initial Implementation for docs

**Related issue(s)**
#684

### CODE REVIEW

**Comment by KhudaDad414** [comment]
@Shurtu-gal Hey man, I want to be a part of this initiative and provide some help if I can. For that, I tried to migrate the studio to Next.js before and faced some challenges but overall it was smooth.

But I had to have `"use client"`on my main page and it was working as a SPA without any features of Next.js in it.

Can you provide what the challenge is here? And how you are trying to resolve it? 🙏

**Comment by Shurtu-gal** [comment]
@KhudaDad414 this is the error which I have been facing for the last couple of days. 
https://app.netlify.com/sites/studio-next/deploys/65f8a395c20fb40008bfa630#L210-L233

**Comment by KhudaDad414** [comment]
@Shurtu-gal the error seems... strange to say the least.
I have uploaded my version of the studio in next here: https://github.com/KhudaDad414/studio/tree/playground-next

it works great in dev and builds fine. There may be some rough edges that we need to iron out.

**Comment by Shurtu-gal** [comment]
> But I had to have "use client"on my main page and it was working as a SPA without any features of Next.js in it

@KhudaDad414 then is there any benefit in shifting to Next.js then 🤔

**Comment by Shurtu-gal** [comment]
I believe there was a misunderstanding. It will be like `AsyncAPI doc` in the browser but will get parsed over at the server. 

However, while writing this I can think of the disadvantages as well, as there will be too many calls to the API functions.

**Comment by Amzani** [comment]
@Shurtu-gal, @KhudaDad414 there are no immediate benefits, but this will unlock a couple of features:

- Completely remove `server-api` dependency and make the code/doc generation/conversion on the server side.
- Enable server side plugins  (auth...)
- Enable APIs: (e.g. Synchronisation with IDEs extensions...)
- https://github.com/asyncapi/studio/issues/224
- Potential performance improvement

If we have an alternative to `nextjs` to enable that I'm fine with it

**Comment by Shurtu-gal** [comment]
So should I move forward with using 'use client' everywhere?

But I believe this will cause problems down the line 😔.

Maybe 🤔 we could resolve this, let me debug it a little

Also @KhudaDad414 @Amzani your help and inputs would be great too.

**Comment by KhudaDad414** [comment]
@Shurtu-gal I am afraid there is no other way.

**Comment by Amzani** [comment]
@Shurtu-gal @KhudaDad414 what if we use `use client` at layout level ? so we don't need to repeat it in each component.

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal @KhudaDad414 what if we use `use client` at layout level ? so we don't need to repeat it in each component.

That would work, let me try it out and I will let you know.

**Comment by Amzani** [comment]
@Shurtu-gal @KhudaDad414 NextJS might sound useless in the beginning, especially as the components are tightly coupled to Browser API, for instance, the TopBar might directly use browser Local storage, so we can't make it a Server Side component.

Once we complete the migration we can follow this pattern that @fmvilas defined in the following: https://github.com/asyncapi/studio/pull/739/files (this is still relevant), so a component like TopBar could be a server-side component for instance.

**Comment by Shurtu-gal** [comment]
> > @Shurtu-gal @KhudaDad414 what if we use `use client` at layout level ? so we don't need to repeat it in each component.
> 
> That would work, let me try it out and I will let you know.

I tried that, but it is showing the same errors. Furthermore @KhudaDad414 your implementation is also not working. FYI there was a similar try in this direction before too in this [PR](https://github.com/asyncapi/studio/pull/701).

**Comment by KhudaDad414** [comment]
@Shurtu-gal let me give it a try. 🤔

**Comment by KhudaDad414** [comment]
Hey @Shurtu-gal, I have opened [a PR](https://github.com/asyncapi/studio/pull/1062) with a solution. (there were too much complications pushing the changes to this PR)
please let me know what you think.

**Comment by Shurtu-gal** [comment]
@KhudaDad414 I am fine with it. @Amzani I guess as there are not many changes to the original app, we should wait before we migrate to CodeMirror. Or I can do it again after the migration PR gets merged.

Closing this PR then.

**Pull request closed without merging**
