### PR TITLE
feat: add spec 3.0 validation support

### PR DESCRIPTION
**Pull request by Amzani**
Fixes https://github.com/asyncapi/studio/issues/746

- Updated dependencies
- Upgraded `@asyncapi/specs` version from `4.2.1 `to `6.0.0-next-major-spec.2` including adapting to breaking changes
- UI Part is done
- 2.x.x to 3.0.0 Conversion is working

### When editing a V3 Async API document

Screenshot 2023-07-28 at 14 47 58

### 2.x.x to 3.0.0 Conversion

Screenshot 2023-07-28 at 14 49 00

Still need to figure out
- **The validation is still not working as @smoya is refactoring ParserJS to support schema validation**
- We should add the V3 support as an option in studio setting as it's weird to enable the conversion to 3.0.0 for all users by default as the tooling support of that version is still in progress.

Screenshot 2023-07-28 at 15 17 40

Any ideas folks ?

### CODE REVIEW

**Review by KhudaDad414 — COMMENTED** [review]
Have been playing around with changes in this PR and the conversion pop-up behaviour seems odd:
1) when the `support v3` toggle is on, and I am editing a v3 document, and I select `new File` it goes black to normal settings and v2. I expect it to show me a window if I want to convert the example to v3.
2) When I am editing a v2 document and I turn the `support v3` toggle on, nothing happens. I expect the conversion pop-up to show up.

**Comment by Amzani** [comment]
> Have been playing around with changes in this PR and the conversion pop-up behaviour seems odd:
> 
> 1. when the `support v3` toggle is on, and I am editing a v3 document, and I select `new File` it goes black to normal settings and v2. I expect it to show me a window if I want to convert the example to v3.

@KhudaDad414 what do you mean by "it goes back to normal settings" ? the `support V3` in setting is toggled off ?

The normal behaviour of the conversion window that shows during edition is the following :
- Asked only one time! during edition
- If you answer no → you need to wait 24h or you have to delete the `informed-about-latest` in sessionStorage

> 2. When I am editing a v2 document and I turn the `support v3` toggle on, nothing happens. I expect the conversion pop-up to show up.

Fixed in my last commits

**Comment by Amzani** [comment]
@smoya the validation works with the last Parser-JS update. 

Screenshot 2023-08-01 at 17 33 59

Screenshot 2023-08-01 at 17 33 33

IMO it's already useful for doc contributors and can be merged. This is a [loom](https://www.loom.com/share/460179f5b8db4c889d74ab8e5ccab5a3?sid=461eea57-3d39-4e5e-9f2a-1b8e7b75819d) on how it works: 

cc @alequetzalli @derberg

**Comment by smoya** [comment]
> @smoya the validation works with the last Parser-JS update.

Clarifying it works because Studio runs an additional JSON Schema validation through the `yaml-schema` Monaco plugin. validation in parser is still WIP (blocked, see https://github.com/asyncapi/parser-js/pull/825#issuecomment-1660419168).

**Comment by smoya** [comment]
@Amzani I love seeing how this is starting to look! 🙌 
Do you think it would be possible to show a popup suggesting to enable v3 validation when a document with version 3 is detected?

**Comment by Amzani** [comment]
@smoya I think we could just have an other setting to enable/disable the spectral validation of v3 documents.

**Review by KhudaDad414 — APPROVED** [review]
LGTM

**Review by KhudaDad414 — APPROVED** [review]

**Pull request merged**
