### PR TITLE
feat: add pitch issue template

### PR DESCRIPTION
**Pull request by Amzani**
**Description**

As part of implementing ShapeUp methodology proposed in [this issue](https://github.com/asyncapi/studio/issues/659), I would like to create a new template for Pitch submissions.

This will simplify the creation of this kind of issues.

**Related issue(s)**

See also https://github.com/asyncapi/studio/issues/659

### CODE REVIEW

**Comment by Amzani** [comment]
@fmvilas ?

**Review by fmvilas — APPROVED** [review]
:shipit:

**Review by fmvilas — APPROVED** [review]

**Pull request merged**
