### PR TITLE
chore: make it a monorepo with the design system

### PR DESCRIPTION
**Pull request by fmvilas**
### Description

It adds Turborepo to the project and makes it a monorepo with two apps: studio and design-system.

### Related issue(s)
See also #637 

### Blocked by
#651

### CODE REVIEW

**Comment by fmvilas** [comment]
I just need to figure out how we're gonna make the automatic releases work. The current GitHub actions are not ready for monorepos. For instance, I'd not like to release a new version of the design-system every time there's a new version of Studio.

**Comment by fmvilas** [comment]
@KhudaDad414 maybe you know how we could handle this? I found [this package](https://github.com/pmowrer/semantic-release-monorepo) but not sure if it's helpful.

**Comment by Amzani** [comment]
@fmvilas @KhudaDad414 In [TurboRepo documentation](https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing) they are mentioning [changesets](https://github.com/changesets/changesets) it worth to take a look as well.

**Comment by KhudaDad414** [comment]
@fmvilas @Amzani I am checking out the Turborepo docs and Changesets docs. will get back here with a solution...

**Comment by Amzani** [comment]
@fmvilas how do we plan to use the components created in the design library ?

I see that in [turborepo](https://turbo.build/) we have`design-system` inside `apps` directory, if we want to make the app reusable the convention of turobrepo is to create it under `packages`

I suggest to Keep `design-system` as an app, that will contain stories and docs, and create a new `ui` directory under `packages`, the ui directory will expose components we create for both `design-system` and `studio`

Some example scan be seen here 
- https://github.com/vercel/turbo/tree/main/examples/with-tailwind
- https://github.com/vercel/turbo/tree/main/examples/design-system

**Comment by fmvilas** [comment]
> @fmvilas how do we plan to use the components created in the design library ?
> 
> I see that in [turborepo](https://turbo.build/) we have`design-system` inside `apps` directory, if we want to make the app reusable the convention of turobrepo is to create it under `packages`
> 
> I suggest to Keep `design-system` as an app, that will contain stories and docs, and create a new `ui` directory under `packages`, the ui directory will expose components we create for both `design-system` and `studio`
> 
> Some example scan be seen here
> 
>     * https://github.com/vercel/turbo/tree/main/examples/with-tailwind
> 
>     * https://github.com/vercel/turbo/tree/main/examples/design-system

Yes, I was following these tutorials and have the `package/ui` folder in my machine but it wasn't committed because it's still empty. Will rework the stuff in this PR in the meantime @KhudaDad414 finds a solution with automation.

**Comment by fmvilas** [comment]
Alright so it's done, I think. We got the design system along with Studio. It's really basic and there are tons of things to improve but this PR is already huge and difficult to review so I'm not going to add more noise for now. Once we figure out release automation, we can proceed to merge if the code owners approve it.

**Review by magicmatatjahu — APPROVED** [review]
LGTM!

**Comment by fmvilas** [comment]
@KhudaDad414 what do you think will happen after I merge? 🤣 Shall I? 😝

**Comment by KhudaDad414** [comment]
@fmvilas are the studio tests passing for you? 🤔

**Comment by fmvilas** [comment]
They are. For me and for CI, apparently. Lots of warnings though. Aren't they passing for you?

**Pull request merged**
