### PR TITLE
feat: adding onboarding documentation to studio

### PR DESCRIPTION
**Pull request by yashsehgal**
**Description**

This PR contains the implementation of the Onboarding Documentation Feature. Referring #284 

- [x] Creating a modal for showing documentation for onboarding
- [x] Adding swiping/sliding functionalities to all the slides for better UX
- [ ] Creating the component customizable with JSON files

**Related issue(s)**

- #284

### CODE REVIEW

**Comment by mcturco** [comment]
@yashsehgal Should we convert this PR to a draft for now? I think there is still some work to be done from a content and visual perspective, and as I see the modal is not quite working atm

**Comment by magicmatatjahu** [comment]
@yashsehgal Hi! Do you need some help there? :)

**Comment by magicmatatjahu** [comment]
@yashsehgal Do you have a time to work on it?

**Comment by fmvilas** [comment]
Since Studio is still in beta, I would hold this one. We're likely gonna change it a lot in the upcoming months, most probably breaking the onboarding. I think a good time to do it would be once we have a release candidate for version 1.0.0.

**Comment by KhudaDad414** [comment]
This PR has been marked as draft so we can ignore it for now till we have the 1.0 version ready.

**Pull request closed without merging**
