### PR TITLE
refactor: change logo of the AsyncAPI Studio, update OG image and icons

### PR DESCRIPTION
**Pull request by Namyalg**
**Description**

The logo on the home page and preload page is changed to the new logo as provided in issue #289 

Updated results

Home page
image

Preload page
image

### CODE REVIEW

**Comment by mcturco** [comment]
@Namyalg This is looking AWESOME! ✨ 

A couple things that I am seeing, and I recorded a loom video sharing my screen so that I can explain better what I mean.

[image <br> feat: changed the Async API studio logo in the navbar, preload page #291 - Watch Video](https://www.loom.com/share/5a403e3edcbe4f6da8d055cdbc55a41b)

**And here's a summary of those points in text:**
1. Spacing to the left of the logo: align square part of logo center to the column below. I am okay with the spacing matching on the other side where the social icons are as well.
2. The logo size needs to be adjusted to 124px wide (auto height)
3. Adjust spacing of `beta` label to match the space shown in figma (I believe it is 9px, but we can adjust it to 8px if that is easier when using rem)
4. Should we change beta label to uppercase like shown in figma file?
5. If we are able to, I think it would be best to align the `beta` label to the baseline of `Studio` in the logo

**Comment by magicmatatjahu** [comment]
@Namyalg Any update?

**Comment by Namyalg** [comment]
Sorry for the delayed response 
But I wasn't exactly able to make the changes as needed

**Comment by magicmatatjahu** [comment]
@mcturco I propagated your suggestions and also I updated OG image. Let me know if changes are ok :)

**Comment by mcturco** [comment]
@magicmatatjahu thank you! this is looking good!
One last thing... can we add `mr-1` class to the `img` tag with the logo in it? I think we just need a little bit more space in between the logo and the `BETA` label.

After that, it is good to go!

**Comment by magicmatatjahu** [comment]
@mcturco Thanks for quick review! I added `ml-1` to the `BETA` label - this same logic but in different way :) WDYT?

**Comment by mcturco** [comment]
@magicmatatjahu awesome, looks good!
Okay last thing that I am just noticing, perhaps we should also update the favicons in this PR? But we could do it in a separate PR if you prefer.

Here is an updated favicon package in case you want to switch them here:
[studio-favicons.zip](https://github.com/asyncapi/studio/files/8428318/studio-favicons.zip)

**Comment by magicmatatjahu** [comment]
@mcturco Thanks very much (again)! I changed icons.

**Comment by magicmatatjahu** [comment]
I also changed prefix for commit to `refactor:` - we don't need to publish new version of studio to the npm (Netlify will deploy new version to server, don't worry), because that PR doesn't have any "new" features.

**Review by mcturco — APPROVED** [review]
Looks good, thank you @magicmatatjahu and @Namyalg!! 🚢

**Pull request merged**
