### PR TITLE
fix: redesign logo and sidebar components

### LINKED ISSUE #671: Sidebar component
Implement the Sidebar component as seen in the [design](https://www.figma.com/file/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=0%3A1&t=5t1QnTliI6risXyA-1).

Captura de pantalla 2023-06-16 a las 8 36 13

Related to #636

### LINKED ISSUE #672: Logo component
Implement the Logo component as seen in the [design](https://www.figma.com/file/bPMB3lkMTOOMuKk0oGLuNm/Studio?type=design&node-id=0%3A1&t=5t1QnTliI6risXyA-1) (the one on the top of the sidebar).

### PR DESCRIPTION
**Pull request by fmvilas**
Fixes #671 
Fixes #672 

Preview Logo: https://deploy-preview-683--asyncapi-studio-design-system.netlify.app/?path=/story/components-logo--default

Preview Sidebar: https://deploy-preview-683--asyncapi-studio-design-system.netlify.app/?path=/story/components-sidebar--with-top-and-bottom-items

### CODE REVIEW

**Comment by fmvilas** [comment]
Will check why the build is failing...

**Comment by KhudaDad414** [comment]
> Will check why the build is failing...

I see the build has been successful, but failed. 🤔

**Review by KhudaDad414 — APPROVED** [review]
LGTM!

**Comment by fmvilas** [comment]
> > Will check why the build is failing...
> 
> I see the build has been successful, but failed. 🤔

It's not successful: https://app.netlify.com/sites/asyncapi-studio-design-system/deploys/64933182db73170008aef0ab

**Comment by fmvilas** [comment]
It's working now. Studio build was failing because of a problem with the cache on Netlify.

**Review by KhudaDad414 — DISMISSED** [review]

**Comment by KhudaDad414** [comment]
@fmvilas I think we should wait for https://github.com/asyncapi/studio/pull/688 and merge this PR after that. if the work is done I will merge this after that PR to test the release process.

I am trying to test that PR to make sure that it can publish to docker without any issues.

**Comment by fmvilas** [comment]
Ok, then let's make sure we change this PR from `chore:` to something else to see if it works.

**Review by KhudaDad414 — APPROVED** [review]

**Pull request merged**
