### PR TITLE
chore: add Khuda as code owner

### PR DESCRIPTION
**Pull request by fmvilas**
I'd love to invite @KhudaDad414 to become a code owner of this repo. Since the rest of the code owners are not very active lately and we want to move the project forward with the new Studio vision and plans: #634. He's already a TSC member so I figured he was the best candidate for now.

### CODE REVIEW

**Review by magicmatatjahu — APPROVED** [review]
Welcome to the codeowners!

**Review by magicmatatjahu — APPROVED** [review]

**Comment by fmvilas** [comment]
Welcome, @KhudaDad414!

**Comment by KhudaDad414** [comment]
Thanks @fmvilas 🥳

**Pull request merged**
