### PR TITLE
[ADR-0006] Use PNPM package manager

### PR DESCRIPTION
**Pull request by KhudaDad414**
**Description**
- I propose we use pnpm instead of npm in studio

### CODE REVIEW

**Comment by Shurtu-gal** [comment]
> We can add the `pnpm-lock.yaml` and `pnpm-workspace_yaml` as well.

The README should also be changed.

**Comment by KhudaDad414** [comment]
@Shurtu-gal after we have an approval from other code-owners, I can move forward with an another PR implementing the change and making sure it works properly with Turborepo.

**Review by Shurtu-gal — APPROVED** [review]
I myself have been using `pnpm` for quite some time now, and agree with this change 🥳.

**Review by Amzani — APPROVED** [review]
LGTM 🚀

**Pull request merged**
