### PR TITLE
feat: add og tags to studio-next

### PR DESCRIPTION
**Pull request by helios2003**
**Description**
Adds static open graph tags to the studio-next application. 

**Screenshots**
For Twitter:
Screenshot 2024-05-28 234008

For Whatsapp
Screenshot 2024-05-28 234650

Network Tab
Screenshot 2024-05-28 234752

**Known limitation(s)**
The AsyncAPI image does not get rendered when sharing the link on Slack but works on all other social media platforms.

**Related issue(s)**

Since https://github.com/asyncapi/studio/issues/224 has been chosen for this year's GSoC I will add incremental improvements and bring it closer to the actual project which includes making the ``og-tags`` as well the `og-image` dynamic.

### CODE REVIEW

**Comment by KhudaDad414** [comment]
@helios2003 there is some effort to generate the graph from the content of the AsyncAPI file here: https://github.com/asyncapi/studio/issues/224

**Comment by KhudaDad414** [comment]
You can close the issue, since it causes conflicts with the work being done over there.

**Comment by helios2003** [comment]
> @helios2003 there is some effort to generate the graph from the content of the AsyncAPI file here: #224

This was a GSoC issue and this PR is a part of the issue.

**Review by KhudaDad414 — CHANGES_REQUESTED** [review]
can you also include one small change so the release pipeline gets unblocked here?
can you [remove this changeset](https://github.com/asyncapi/studio/blob/master/.changeset/odd-rules-accept.md) ?

**Review by KhudaDad414 — APPROVED** [review]
LGTM

**Comment by KhudaDad414** [comment]
@helios2003 feel free to merge when ready.

**Pull request merged**
