### PR TITLE
fix: Disable unsupported generators for AsyncAPI V3 (#979)

### LINKED ISSUE #979: Disable the generators that are not yet supported in V3
Some generators don't support yet V3

- @asyncapi/dotnet-nats-template
- @asyncapi/ts-nats-template
- @asyncapi/python-paho-template
- @asyncapi/nodejs-ws-template
- @asyncapi/java-spring-cloud-stream-template
- @asyncapi/go-watermill-template
- @asyncapi/java-spring-template
- @asyncapi/nodejs-template
- @asyncapi/java-template
- @asyncapi/php-template

## Current behavior

In V3 document ([example](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6IDMuMC4wCmluZm86CiAgdGl0bGU6IEFjY291bnQgU2VydmljZQogIHZlcnNpb246IDEuMC4wCiAgZGVzY3JpcHRpb246IFRoaXMgc2VydmljZSBpcyBpbiBjaGFyZ2Ugb2YgcHJvY2Vzc2luZyB1c2VyIHNpZ251cHMKY2hhbm5lbHM6CiAgdXNlclNpZ25lZHVwOgogICAgYWRkcmVzczogdXNlci9zaWduZWR1cAogICAgbWVzc2FnZXM6CiAgICAgIFVzZXJTaWduZWRVcDoKICAgICAgICAkcmVmOiAnIy9jb21wb25lbnRzL21lc3NhZ2VzL1VzZXJTaWduZWRVcCcKb3BlcmF0aW9uczoKICBzZW5kVXNlclNpZ25lZHVwOgogICAgYWN0aW9uOiBzZW5kCiAgICBjaGFubmVsOgogICAgICAkcmVmOiAnIy9jaGFubmVscy91c2VyU2lnbmVkdXAnCiAgICBtZXNzYWdlczoKICAgICAgLSAkcmVmOiAnIy9jaGFubmVscy91c2VyU2lnbmVkdXAvbWVzc2FnZXMvVXNlclNpZ25lZFVwJwpjb21wb25lbnRzOgogIG1lc3NhZ2VzOgogICAgVXNlclNpZ25lZFVwOgogICAgICBwYXlsb2FkOgogICAgICAgIHR5cGU6IG9iamVjdAogICAgICAgIHByb3BlcnRpZXM6CiAgICAgICAgICBkaXNwbGF5TmFtZToKICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgIGRlc2NyaXB0aW9uOiBOYW1lIG9mIHRoZSB1c2VyCiAgICAgICAgICBlbWFpbDoKICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgIGZvcm1hdDogZW1haWwKICAgICAgICAgICAgZGVzY3JpcHRpb246IEVtYWlsIG9mIHRoZSB1c2Vy)) not supported generators are displayed even though they are not supported.

Screenshot 2024-02-27 at 13 31 24

## Expected behavior

For a better Developer Experience(DX):

- Disable not supported generators
- Inform the user

Screenshot 2024-02-27 at 13 38 44

Tracking link: https://github.com/asyncapi/studio/issues/980

Note: Currently there is a bug in the Doc generation for V3, the fix is WIP https://github.com/asyncapi/cli/pull/1200

### PR DESCRIPTION
**Pull request by kalpesh-d**
**Description**

- Updated the GeneratorModal component to disable unsupported generators for AsyncAPI V3.
- Added a warning message for unsupported generators with a link to the tracking page.

**Related issue(s)**
Fixes #979

### CODE REVIEW

**Review by Amzani — CHANGES_REQUESTED** [review]
Thanks @kalpesh-d for this PR.
This behavior should only happen for AsyncAPI V3 documents. 
For older versions all generators are working - try with [this](https://gist.githubusercontent.com/dalelane/62803461d2c1df5577c89e38785b7f81/raw/aab4446d44804693a7723a71e4cb61534ffc9157/asyncapi-example.yaml) for instance

**Review by kalpesh-d — COMMENTED** [review]
Hi @Amzani, Changes have been made to ensure that only AsyncAPI V3 documents exhibit this behavior, while older versions continue to support all generators.

**Review by Amzani — CHANGES_REQUESTED** [review]
Some linting errors

**Review by kalpesh-d — COMMENTED** [review]
Hi @Amzani, I've addressed linting errors in the code. Everything should be in order now.

**Review by Amzani — APPROVED** [review]

**Pull request merged**
