### PR TITLE
feat: add error toasts when loading from "url"  query paramater

### PR DESCRIPTION
**Pull request by ppfenning92**
**Description**

- Adds error toasts notifying users when fetching spec via `url` query paramater fails

### CODE REVIEW

**Comment by fmvilas** [comment]
@magicmatatjahu would you mind having a look, please?

**Comment by Amzani** [comment]
cc @KhudaDad414

**Review by KhudaDad414 — COMMENTED** [review]
@ppfenning92 it works great if the url is broken. can you also cover the case when the url returns `404` error? like this one: https://raw.githubusercontent.com/asyncapi/spec-json-schemas/ff3ab77b5bbad0ff05eabc4b10c8685638dcc4a7/examples/2.6.0/componnts.json

**Comment by ppfenning92** [comment]
@KhudaDad414 sure, give me some time, very busy these days....

**Comment by KhudaDad414** [comment]
@ppfenning92 sure man. just let me know when it is ready for review.

**Comment by Amzani** [comment]
@ppfenning92 could you fix the conflicts
Thanks

**Comment by ppfenning92** [comment]
image

screenshot for clarity :)

**Comment by jonaslagoni** [comment]
@KhudaDad414 can you have a look here?

**Pull request merged**
