### PR TITLE
chore: make v3 default

### LINKED ISSUE #832: Make v3 default
Currently users needs to enable V3 to use it.
Screenshot 2023-10-26 at 14 31 37

We want to make the `enable v3 support` as default. 

Related to https://github.com/asyncapi/studio/issues/641

### PR DESCRIPTION
**Pull request by Shurtu-gal**
**Description**

- Make v3 as the default
- When loading V3 is default

**Related issue(s)**
Fixes #832

### CODE REVIEW

**Comment by Shurtu-gal** [comment]
@Amzani Should I update the default doc as well?

**Comment by Amzani** [comment]
/progress 80

Read to review

**Review by KhudaDad414 — APPROVED** [review]
LGTM! 🙇  lets wait for @Amzani review.

**Comment by Amzani** [comment]
LGTM, however let's merge it once we fix https://github.com/asyncapi/studio/pull/842

**Review by Amzani — APPROVED** [review]

**Comment by Shurtu-gal** [comment]
> LGTM, however let's merge it once we fix #842

Sorry, didn't see this and added the ready-to-merge label by force of habit 😿 . Should I revert it?

**Pull request merged**
