### PR TITLE
feat: migrate to next

### LINKED ISSUE #684: Minimal studio App with a working editor and AsyncAPI documentation
As part of the discussion in #661, I'm creating this issue to track the migration since it's a huge task.

Related to #661

### PR DESCRIPTION
**Pull request by Shurtu-gal**
#### Description:- 
This is made to migrate the current react framework to NextJs 13

- [x] Install Basic packages for next and initialise it 
- [x] Add tailwind support
- [x] Setup web pack
- [ ] Setup services correctly to run on the server,
- [x] Add support for MonacoEditor
- [ ] Add loader for YAML and JSON files.
- [ ] Clean up the packages
- [ ] Update the actions
- [ ] Write some basic tests.

#### Related issues:-
Resolves #684

### CODE REVIEW

**Comment by fmvilas** [comment]
Can you please edit the description of this PR and add "resolves #684"? This way GitHub would link this PR to the issue :)

**Comment by Shurtu-gal** [comment]
Done also added some tasks to do it methodologically. Do suggest if something is missing. 😃

**Comment by fmvilas** [comment]
That looks perfect mate 👍

**Comment by Shurtu-gal** [comment]
@fmvilas I have added the hooks architecture. Do tell me if this will work.

**Comment by fmvilas** [comment]
It's amazing mate!  You're doing a great effort 👏 What do you think it's best? I have the feeling that we can't merge this confidently and expect it to work the same as it's in production right now. Do you think it would be best to start development in a separate folder and slowly make sure it's going well?

**Pull request closed without merging**
