### PR TITLE
add architecture considerations document

### PR DESCRIPTION
**Pull request by fmvilas**
**Description**

Some initial considerations for the new Studio architecture.

**Related issue(s)**
#725

### CODE REVIEW

**Comment by Shurtu-gal** [comment]
@fmvilas The problems faced using the current services may also be mentioned.
Going forward, what I propose to do is :- 
 - Hoist shared components such as editor to context and pass them onto hooks [example](https://github.com/Shurtu-gal/studio/blob/feat/migrate-next/apps/studio/src/hooks/useServices.tsx)
 - Use hooks to share the functions and store application logic. [example](https://github.com/Shurtu-gal/studio/tree/feat/migrate-next/apps/studio/src/hooks)

This works well currently; even things such as navigation in the editor, template and visualiser are working correctly.

**Comment by fmvilas** [comment]
@Shurtu-gal I wonder if that's something related to the current architecture. Maybe, with the new architecture, we can find a way to make this easier? I mean, with a couple of exceptions, everything should be executable on the server and on the client. What do you think?

**Comment by Shurtu-gal** [comment]
Yeah, if we separate it instead of maintaining it on the client. These problems will be solved by themselves. This way, the object of concern may be separated, and services may be exposed as APIs. 

P.S.:- But things like navigation and theme setting would have to be handled on the client side using context and hooks.

**Comment by Amzani** [comment]
@fmvilas @Shurtu-gal I think it's a valid question that we should cover under the new architecture ? **When do use Hooks ?** and also **How to share state between components ? do we use React Context or Zustand**

**Comment by fmvilas** [comment]
Agree. We'll have to address all these questions. Who wants to take the lead here?

**Comment by Amzani** [comment]
Still relevant

**Pull request closed without merging**
