### PR TITLE
fix: fix the operation messages paths

### PR DESCRIPTION
**Pull request by KhudaDad414**
Related to: https://asyncapi.slack.com/archives/C34F2JV0U/p1701685416306489?thread_ts=1701618246.696289&cid=C34F2JV0U

### CODE REVIEW

**Review by Amzani — APPROVED** [review]
LGTM

**Comment by Amzani** [comment]
@KhudaDad414 I still see the default [file failing](https://deploy-preview-876--modest-rosalind-098b67.netlify.app/)
I tried with a fresh browser and incognito mode

**Comment by KhudaDad414** [comment]
https://github.com/asyncapi/studio/assets/32505158/bcd03656-be75-4385-8790-ae6f329e0fa2


@Amzani interesting 🤔🤔 working fine for me.

**Pull request merged**
