### PR TITLE
change in index.css

### PR DESCRIPTION
**Pull request by nikhil-3112**
**Description**

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Review by nikhil-3112 — COMMENTED** [review]
Changed index.css
Screenshot (184)
Screenshot 2024-03-08 155941

**Comment by KhudaDad414** [comment]
@nikhil-3112 no changes have been proposed in this PR. please make sure to first open an Issue if you think some changes need to be made.

**Comment by nikhil-3112** [comment]
> @nikhil-3112 no changes have been proposed in this PR. please make sure to first open an Issue if you think some changes need to be made.

@KhudaDad414 @koukama 
I opened the issue and tried finding some files that need to be modify but I was not able to do with my forked repository. Even not able to make changes and submit a pull request. Do i need any permission , if there is kindly allow me.
Thank you.

**Comment by Amzani** [comment]
Hi @nikhil-3112 I think @koukama already submitted a PR https://github.com/asyncapi/studio/pull/1025
You can pick other issues, by commenting that you want to work on them. Regarding your issue, you don't need any permission from us to contribute in your own Fork.

**Pull request closed without merging**
