### PR TITLE
Fix sidebar's color

### LINKED ISSUE #989: Abrupt change in the color of the Navigation sidebar
#### Describe the bug
The color of the Navigation sidebar changes abruptly from the original color to black when the document is invalid

#### How to Reproduce
- Have the navigation sidebar open and create an invalid document.
- The color of the sidebar suddenly changes to black with the error message.
- Screenshots <br />
Present situation 
image <br />
Suggested change
image <br />

#### Expected behavior
- Color should remain the same as the original color like how it remains white in the HTML preview as well. As this would better the User Experience.

### PR DESCRIPTION
**Pull request by helios2003**
**Description**

The sidebar's color remains the same as the original color even when the error message is displayed.
image

**Related issue(s)**
Fixes #989

### CODE REVIEW

**Review by princerajpoot20 — DISMISSED** [review]
LGTM! 🚀 Thanks for your first PR

**Review by Amzani — DISMISSED** [review]
LGTM

**Comment by Amzani** [comment]
Hi @helios2003 
Could you fix this issue: https://sonarcloud.io/component_measures?id=asyncapi_studio&pullRequest=990&metric=new_duplicated_lines_density&view=list

thanks

**Comment by helios2003** [comment]
Sure @Amzani, I will try resolving it.

**Comment by helios2003** [comment]
Hi @Amzani, from what I understand I need to refactor the last 46 lines in ``apps/studio-next/src/state/files.state.ts``. Is that right?

**Comment by princerajpoot20** [comment]
@helios2003 , the file `apps/studio-next/src/state/files.state.ts` contains a duplicate line of code. 
Pinging @Shurtu-gal : could you assist @helios2003 in fixing this as you have recently pushed this.

**Comment by Shurtu-gal** [comment]
The problem is that the following lines are the same and it should be as we want to introduce minimal changes while migrating. At least the states are fine as it is.

https://github.com/asyncapi/studio/blob/f9fbf2d9f4d5e26fcc8914583622c47f7e6c3719/apps/studio-next/src/state/files.state.ts#L212-L255

https://github.com/asyncapi/studio/blob/f9fbf2d9f4d5e26fcc8914583622c47f7e6c3719/apps/studio/src/state/files.state.ts#L212-L255

@Amzani is there any way this rule can be disabled 🤔

**Comment by Amzani** [comment]
@helios2003 @Shurtu-gal as we are migrating code to `studio-next` we can add `studio-next` directory in `.sonarcloud.properties` / `sonar.cpd.exclusions`

**Comment by helios2003** [comment]
@Shurtu-gal  should I add this as a part of the PR or the change should be done by the maintainer itself?

**Comment by Shurtu-gal** [comment]
You can do it in this PR itself.

**Comment by helios2003** [comment]
@Amzani, @Shurtu-gal the changes have been made.

**Comment by Shurtu-gal** [comment]
> @Amzani, @Shurtu-gal the changes have been made.

Great!! Thanks 🤗

**Review by princerajpoot20 — APPROVED** [review]
Great work! @helios2003

**Comment by KhudaDad414** [comment]
@Amzani @Shurtu-gal what about adding `studio` to the Sonar exception list? Since `studio-next` is going to see a lot of activity and by ignoring duplicates in `studio` we can make sure the `studio-next` is duplicate free.

**Comment by Shurtu-gal** [comment]
@KhudaDad414 it is already [there](https://github.com/asyncapi/studio/pull/990/files#diff-679bb064ac2db7c8eab53b5a396d88ac78ebe2444f7d180bfcc0dc0df7b2152cR4) I believe.

**Comment by helios2003** [comment]
Maintainers, if the PR is fine, can it be merged?

**Review by princerajpoot20 — APPROVED** [review]
LGTM

**Review by Amzani — APPROVED** [review]
LGTM

**Comment by KhudaDad414** [comment]
this PR did not result in a release because it did not contain a changeset. https://github.com/asyncapi/studio/pull/990#issuecomment-1983569187 

@Amzani now I understand your frustration. 🤦

**Pull request merged**
